### PR TITLE
Fix unknown type handling

### PR DESCRIPTION
**Pull request by woodyblah**
If you take a look at this commit https://github.com/bbc/stump/commit/62e1a58aa13b06995ffa960a1846d2ee718358c5  

I had a much shorter solution to encoding the tuples for the logs, but I have no idea how far that `encode` method could spread. Potentially any app that uses Jason and Stump would include this implementation of encode, and indeed could also override that implementation.

I went with the more complicated, but more consistent approach of just converting to a type we know works inside Stump itself.

Edit: Philosopher's Stone draft PR https://github.com/bbc/stump/pull/9

I've also added a "raw_log" to the error catcher to help us see what is being presented to the logger when it fails to encode.

### CODE REVIEW

**Comment by JoeARO** [comment]
In the ReadMe there is a version number aswell for the hex installation

**Comment by ettomatic** [comment]
have you seen this https://github.com/philosophers-stone/transform

**Comment by woodyblah** [comment]
That's exactly what we need! I'm going to see how easy/complicated it is to use, and benchmark it for good measure. Looks excellent from the Readme though 👍

**Comment by ettomatic** [comment]
Shame that Philosopher's Stone affects so much the performance 😢 , I'd suggest parking it for now in a branch and bring back your original approach

**Pull request merged**
